### ISSUE TITLE
This SC is not compatible with NEP-10 - contrary to the comment in the code

### ISSUE THREAD

**Issue by mwherman2000** [NeoResearch/nep-distributed-payments#1]
RE: "This example is intended to be the simplest example of NEP10 proposal"

This SC is not compatible with NEP-10.  It doesn't implement the `supportedStandards` method.

Reference: https://github.com/neo-project/proposals/blob/master/nep-10.mediawiki

**Comment by vncoelho** [comment]
Fresh fresh, Thanks Michael Herman.
Could you make a PR with the necessary standards?

**Comment by igormcoelho** [comment]
Ok Michael, this is still an early draft. We intend to include as soon as possible the NEP10 specifications, and also some newer possibilities regarding NEP7. Perhaps in a few days we can have an improved version. For now, the point is just to let the community know of our intentions and start to collect feedback for improvements. Thanks a lot.

**Comment by igormcoelho** [comment]
NEP-10 is now supported: f522de9e17414e73d607935abad8d182686a29c7
